-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "1920x0", scale = 1 })
hl.monitor({ output = "desc:LG Electronics LG FULL HD 0x001C256A", mode = "1920x1080@74.973", position = "1920x0", scale = 1, vrr = 0 })
hl.monitor({ output = "desc:Samsung Electric Company SAMSUNG", mode = "1920x1080@60.000", position = "0x0", scale = 1, vrr = 0 })
